### ISSUE TITLE
Add Default States To All Items

### ISSUE THREAD

**Issue by AlexanderTheGr3at** [Siryphas/Witcher-Compendium#2]
Like some items being consumable, and what they do when you do consume them. Things like that.

**Comment by Siryphas** [comment]
I'm working on creating Global Modifiers for everything, but I don't have a ton of time to devote to it. I've got some of the GMs for Spells, but I still have to do Alchemical Items as well.

**Comment by AlexanderTheGr3at** [comment]
Is it something that needs a deep knowledge of programming to do? If not I can offer up my humble (just learning) services to help.

**Comment by Siryphas** [comment]
Nope, I'm not a coder or programmer at all. I simply make items in Foundry. In this case, Global Modifer Items. Then I attach those Global Modifiers to the Alchemical Items sheets and Spell item sheets. If you want to help out, I'd be more than happy for the assistance. It's not hard, just time consuming and tedious.

**Comment by AlexanderTheGr3at** [comment]
Time consuming and tedious is something I excel at! How do I help out?

**Comment by Siryphas** [comment]
Find me on Discord, under the same name, and I can try to talk you through jt.
